# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0002_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
