# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0003_dog_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='no description', max_length=1000)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
