# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0006_auto_20171213_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
