# Generated by Django 2.0.2 on 2018-03-12 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0009_auto_20180312_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=1000)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
