# Generated by Django 2.0.2 on 2018-03-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0010_otherpets'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='dogage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='maindescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
