# Generated by Django 2.0.2 on 2018-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0011_auto_20180319_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dogage',
            field=models.IntegerField(),
        ),
    ]
