# Generated by Django 2.0.2 on 2018-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0013_auto_20180319_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cat',
            name='catage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cat',
            name='maindescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cat',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='url1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cat',
            name='url2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='maindescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='petage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherpets',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherpets',
            name='url1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='url2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
