# Generated by Django 2.0.2 on 2018-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0015_dog_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='otherpets',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
