# Generated by Django 2.0.2 on 2018-03-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0016_auto_20180329_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='price',
        ),
        migrations.RemoveField(
            model_name='otherpets',
            name='price',
        ),
    ]
