# Generated by Django 2.0.2 on 2018-04-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0017_auto_20180329_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('number', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
