# Generated by Django 2.0.2 on 2018-04-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0018_clientcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('number', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientContacts',
        ),
    ]
