# Generated by Django 2.0.2 on 2018-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0020_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pet_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
