# Generated by Django 2.0.2 on 2018-04-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0021_client_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pet_type',
        ),
    ]
