# Generated by Django 2.0.2 on 2018-04-06 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0022_remove_client_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat'), ('O', 'Other_pet')], max_length=1)),
                ('picture_1', models.CharField(blank=True, default='', max_length=1000)),
                ('picture_2', models.CharField(blank=True, default='', max_length=1000)),
                ('picture_3', models.CharField(blank=True, default='', max_length=1000)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('description', models.TextField(default='')),
                ('main_description', models.TextField(default='')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hidden', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='dog',
        ),
        migrations.DeleteModel(
            name='OtherPets',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
