# Generated by Django 2.0.2 on 2018-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0023_auto_20180406_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other_pet', 'Other_pet')], max_length=1),
        ),
    ]
