# Generated by Django 2.0.2 on 2018-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0026_auto_20180406_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pet_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
