# Generated by Django 2.0.2 on 2018-05-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0027_client_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='main_description',
        ),
    ]
