# Generated by Django 2.0.2 on 2018-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0028_remove_pet_main_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Самец', 'Самец'), ('Самка', 'Самка')], max_length=100),
        ),
    ]
