# Generated by Django 2.0.2 on 2018-05-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pit', '0029_auto_20180518_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
